[mypy]
plugins = mypy_django_plugin.main

[mypy.plugins.django-stubs]
django_settings_module = "config.settings"

[mypy-django_jsonform.*,celery.*,requests_oauthlib.*,allauth.*,vl_convert.*,django_recaptcha.*]
ignore_missing_imports = True
