# Generated by Django 4.1.4 on 2023-01-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="metric",
            old_name="credentials",
            new_name="integration_credentials",
        ),
        migrations.AlterField(
            model_name="metric",
            name="integration_id",
            field=models.CharField(
                choices=[
                    ("github", "github"),
                    ("google_analytics", "google_analytics"),
                    ("google_search_console", "google_search_console"),
                    ("google_sheets", "google_sheets"),
                    ("linkedin", "linkedin"),
                    ("mailchimp", "mailchimp"),
                    ("pipedrive", "pipedrive"),
                    ("plausible", "plausible"),
                    ("postgresql", "postgresql"),
                    ("twitter", "twitter"),
                    ("youtube", "youtube"),
                ],
                max_length=128,
            ),
        ),
    ]
