# Generated by Django 4.1.4 on 2023-02-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_alter_metric_integration_id_dashboard_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="name",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
    ]
