# Generated by Django 4.1.7 on 2023-02-25 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0006_organizationinvitation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="metric",
            name="organizations",
            field=models.ManyToManyField(to="mainapp.organization"),
        ),
        migrations.AlterField(
            model_name="organizationuser",
            name="inviter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inviter",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
