# Generated by Django 4.1.7 on 2023-03-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0009_metric_dashboards_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_dashboard_visit",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="metric",
            name="integration_id",
            field=models.CharField(
                choices=[
                    ("github", "github"),
                    ("google_analytics", "google_analytics"),
                    ("google_cloud_protected_api", "google_cloud_protected_api"),
                    ("google_play_store", "google_play_store"),
                    ("google_search_console", "google_search_console"),
                    ("google_sheets", "google_sheets"),
                    ("grafana", "grafana"),
                    ("linkedin", "linkedin"),
                    ("mailchimp", "mailchimp"),
                    ("pipedrive", "pipedrive"),
                    ("plausible", "plausible"),
                    ("postgresql", "postgresql"),
                    ("twitter", "twitter"),
                    ("youtube", "youtube"),
                ],
                max_length=128,
            ),
        ),
    ]
