# Generated by Django 5.0 on 2023-12-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0011_organization_slack_notifications_channel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="metric",
            name="enable_medals",
            field=models.BooleanField(
                default=True,
                help_text="Will mark with an icon the top 3 values on the graphs",
            ),
        ),
        migrations.AddField(
            model_name="metric",
            name="higher_is_better",
            field=models.BooleanField(
                default=True,
                help_text="Whether or not high values are considered a good outcome",
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="integration_id",
            field=models.CharField(
                choices=[
                    ("github", "github"),
                    ("google_analytics", "google_analytics"),
                    ("google_bigquery", "google_bigquery"),
                    ("google_cloud_protected_api", "google_cloud_protected_api"),
                    ("google_play_store", "google_play_store"),
                    ("google_search_console", "google_search_console"),
                    ("google_sheets", "google_sheets"),
                    ("grafana", "grafana"),
                    ("linkedin", "linkedin"),
                    ("mailchimp", "mailchimp"),
                    ("pipedrive", "pipedrive"),
                    ("plausible", "plausible"),
                    ("postgresql", "postgresql"),
                    ("twitter", "twitter"),
                    ("youtube", "youtube"),
                ],
                max_length=128,
            ),
        ),
    ]
