# Generated by Django 5.0.2 on 2024-03-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0013_alter_metric_enable_medals_marker_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="metric",
            name="last_collect_attempt",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
