# Generated by Django 5.0.3 on 2024-03-23 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def population_metric_organization(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Metric = apps.get_model("mainapp", "Metric")
    for metric in Metric.objects.all():
        organizations = metric.organizations.all()
        if organizations:
            # Take the first one
            metric.organization = organizations[0]
            metric.save()


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0014_metric_last_collect_attempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="metric",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainapp.organization",
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.RunPython(population_metric_organization),
        migrations.RemoveField(
            model_name="metric",
            name="organizations",
        ),
    ]
