# Generated by Django 5.0.4 on 2024-04-25 07:51

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0016_metric_target_alter_metric_enable_medals_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metric",
            name="id",
            field=models.CharField(
                auto_created=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
