# Generated by Django 5.0.4 on 2024-04-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0019_alter_metric_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="metric",
            name="dashboards",
        ),
    ]
