# Generated by Django 5.0.6 on 2024-07-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0021_metric_description_alter_metric_integration_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="metric",
            name="should_backfill_daily",
            field=models.BooleanField(
                default=False, help_text="Backfill daily (experimental)"
            ),
        ),
    ]
