# Generated by Django 5.1.6 on 2025-04-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0023_metric_last_detected_spike_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="metric",
            name="enable_spike_notifications",
            field=models.BooleanField(
                default=True,
                help_text="Whether or not to send notifications about spikes",
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="integration_id",
            field=models.CharField(
                choices=[
                    ("bluesky", "bluesky"),
                    ("facebook", "facebook"),
                    ("github", "github"),
                    ("google_analytics", "google_analytics"),
                    ("google_bigquery", "google_bigquery"),
                    ("google_cloud_protected_api", "google_cloud_protected_api"),
                    ("google_play_store", "google_play_store"),
                    ("google_search_console", "google_search_console"),
                    ("google_sheets", "google_sheets"),
                    ("grafana", "grafana"),
                    ("instagram", "instagram"),
                    ("linkedin", "linkedin"),
                    ("mailchimp", "mailchimp"),
                    ("pipedrive", "pipedrive"),
                    ("plausible", "plausible"),
                    ("postgresql", "postgresql"),
                    ("posthog", "posthog"),
                    ("stripe", "stripe"),
                    ("threads", "threads"),
                    ("twitter", "twitter"),
                    ("youtube", "youtube"),
                ],
                max_length=128,
            ),
        ),
    ]
